# Base information
baseURL = "https://ess.fyi"
languageCode = "en-gb"
title = "ESS"
theme = "hugo-developer-portfolio"
googleAnalytics = ""
 
[module]
  [[module.imports]]
    path = "github.com/samrobbins85/hugo-developer-portfolio"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"


# navigation
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight=1

  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  weight=2

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight=3



[params]
home = "Home"
# Meta data
description = "Technical Writer, Occasional Godlike Genius"
author = "Elizabeth Sinclair-Smith"


  [params.contact]
  enable = false
  formAction = "" #contact form works with formspree.io

  [params.footer]
  email = "ss.elizabeth@gmail.com"
  address = "South San Francisco, CA"
  googlemaps = "https://www.google.com/maps/place/South+San+Francisco,+CA/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "rainbow_dash"
    tabWidth = 4

