name = "Developer Portfolio"
license = "MIT"
licenselink = "https://github.com/samrobbins85/hugo-developer-portfolio/blob/master/LICENSE"
description = "A Portfolio website designed for developers"
homepage = "https://github.com/samrobbins85/hugo-developer-portfolio"
tags = ["portfolio", "developer", "responsive","uikit"]
features = ["uikit", "responsive", "features"]
min_version = "0.54.0"

[author]
    name = "Sam Robbins"
    homepage = "https://samrobbins.uk/"

